# -*- coding: utf-8 -*-
"""0629_실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EvsUlgcDsUtlf0k_Y52BTNhGHGeI6RyH

6-2 데이터를 리서치하거나 주어진 데이터의 위치 정보를 활용하여 지도 시각화를 하고, 이를 html 파일로 생성해 보자.
(코드 : .py, 파일 : 구글 드라이브에 공유 폴더에 올리기)
"""

import pandas as pd

df = pd.read_csv('공공데이터활용지원센터_코로나19 예방접종센터 현황_20210611.csv', engine = 'python', encoding='cp949')

df.head(5)

df.columns

df.info()

df_tmp = df.loc[ :, ['시설명', 'Y', 'X' ]   ]
df_tmp

# 중앙 위치 찾기
df_tmp.columns = ['시설명', 'Y', 'X' ]
print( df_tmp.Y.mean(), df_tmp.X.mean() )

import folium

loc = folium.Map(location=[36.45979185193306, 127.60867010520442], zoom_start=8)

folium.Marker([37.567817, 127.004501]).add_to(loc) # 국립중앙의료원
folium.Marker([36.779887,127.164717]).add_to(loc) # 순천향대 천안병원	
loc

loc = folium.Map(location=[36.45979185193306, 127.60867010520442], zoom_start=8)

N = 269
for i in range(N):
  folium.Marker(location= [ df.loc[i, 'Y']  , df.loc[i, 'X'] ] ,
                tooltip= df.loc[i, '시설명']  ,
          ).add_to(loc)

loc

loc.save('공공데이터활용지원센터_코로나19 예방접종센터 현황_20210611.html')
import os
os.getcwd()